[phases.setup]
nixPkgs = ["nodejs-18_x", "python311", "python311Packages.pip", "python311Packages.setuptools"]

[phases.install]
cmds = [
  "npm ci",
  "pip install -e ../../sec-edgar-mcp"
]

[start]
cmd = "npm start"