[phases.setup]
nixPkgs = ["nodejs-18_x", "python311", "python311Packages.pip", "python311Packages.setuptools"]

[phases.install]
cmds = [
  "npm ci", 
  "pip install -r requirements.txt",
  "cp -r ../../sec-edgar-mcp ./sec-edgar-mcp",
  "pip install -e ./sec-edgar-mcp"
]

[start]
cmd = "npm start"